server:
  http:
    addr: 0.0.0.0:8000
    timeout: 900s
data:
  database:
    driver: mysql
    source: root:${MYSQL_PASSWORD}@tcp(mysql:3306)/ayana?parseTime=True&loc=Local
  redis:
    addr: redis:6379
    password: ${REDIS_PASSWORD}
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 1s
  kafka:
    addr: kafka:9094
    topic: "ayana_seminar_tokens"
    partition: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: jaeger:4318

service:
  user:
    endpoint: discovery:///Ayana.service.user
  role:
    endpoint: discovery:///Ayana.service.role
  seminar:
    endpoint: discovery:///Ayana.service.seminar
  
