server:
  http:
    addr: 0.0.0.0:8000
    timeout: 20s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/ayana?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: "test"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 1s
trace:
  endpoint: 127.0.0.1:4318

service:
  user:
    endpoint: discovery:///Ayana.service.user
  role:
    endpoint: discovery:///Ayana.service.role
  seminar:
    endpoint: discovery:///Ayana.service.seminar
  
