server:
  grpc:
    addr: 0.0.0.0:9002
    timeout: 10s

data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/ayana?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: "test"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 1s
  kafka:
    addr: localhost:9094
    topic: "ayana_seminar_tokens"
    partition: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
  milvus:
    endpoint: 127.0.0.1:19530
    collection: "ayana_documents"
    ApiKey: "root:Milvus"

trace:
  endpoint: 127.0.0.1:4318


service:
  role:
    endpoint: discovery:///Ayana.service.role
  


