// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: gateway/role/v1/role.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoleManager_CreateRole_FullMethodName         = "/Wittgenstein.v1.RoleManager/CreateRole"
	RoleManager_DeleteRole_FullMethodName         = "/Wittgenstein.v1.RoleManager/DeleteRole"
	RoleManager_GetRoles_FullMethodName           = "/Wittgenstein.v1.RoleManager/GetRoles"
	RoleManager_GetRolesByUIDs_FullMethodName     = "/Wittgenstein.v1.RoleManager/GetRolesByUIDs"
	RoleManager_GetAvailableModels_FullMethodName = "/Wittgenstein.v1.RoleManager/GetAvailableModels"
	RoleManager_SetRole_FullMethodName            = "/Wittgenstein.v1.RoleManager/SetRole"
)

// RoleManagerClient is the client API for RoleManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleManagerClient interface {
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleReply, error)
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleReply, error)
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesReply, error)
	GetRolesByUIDs(ctx context.Context, in *GetRolesByUIDsRequest, opts ...grpc.CallOption) (*GetRolesByUIDsReply, error)
	GetAvailableModels(ctx context.Context, in *GetAvailableModelsRequest, opts ...grpc.CallOption) (*GetAvailableModelsReply, error)
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleReply, error)
}

type roleManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleManagerClient(cc grpc.ClientConnInterface) RoleManagerClient {
	return &roleManagerClient{cc}
}

func (c *roleManagerClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleReply)
	err := c.cc.Invoke(ctx, RoleManager_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManagerClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleReply)
	err := c.cc.Invoke(ctx, RoleManager_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManagerClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolesReply)
	err := c.cc.Invoke(ctx, RoleManager_GetRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManagerClient) GetRolesByUIDs(ctx context.Context, in *GetRolesByUIDsRequest, opts ...grpc.CallOption) (*GetRolesByUIDsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolesByUIDsReply)
	err := c.cc.Invoke(ctx, RoleManager_GetRolesByUIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManagerClient) GetAvailableModels(ctx context.Context, in *GetAvailableModelsRequest, opts ...grpc.CallOption) (*GetAvailableModelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableModelsReply)
	err := c.cc.Invoke(ctx, RoleManager_GetAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleManagerClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoleReply)
	err := c.cc.Invoke(ctx, RoleManager_SetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleManagerServer is the server API for RoleManager service.
// All implementations must embed UnimplementedRoleManagerServer
// for forward compatibility.
type RoleManagerServer interface {
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleReply, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleReply, error)
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesReply, error)
	GetRolesByUIDs(context.Context, *GetRolesByUIDsRequest) (*GetRolesByUIDsReply, error)
	GetAvailableModels(context.Context, *GetAvailableModelsRequest) (*GetAvailableModelsReply, error)
	SetRole(context.Context, *SetRoleRequest) (*SetRoleReply, error)
	mustEmbedUnimplementedRoleManagerServer()
}

// UnimplementedRoleManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleManagerServer struct{}

func (UnimplementedRoleManagerServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedRoleManagerServer) DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedRoleManagerServer) GetRoles(context.Context, *GetRolesRequest) (*GetRolesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoles not implemented")
}
func (UnimplementedRoleManagerServer) GetRolesByUIDs(context.Context, *GetRolesByUIDsRequest) (*GetRolesByUIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolesByUIDs not implemented")
}
func (UnimplementedRoleManagerServer) GetAvailableModels(context.Context, *GetAvailableModelsRequest) (*GetAvailableModelsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableModels not implemented")
}
func (UnimplementedRoleManagerServer) SetRole(context.Context, *SetRoleRequest) (*SetRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedRoleManagerServer) mustEmbedUnimplementedRoleManagerServer() {}
func (UnimplementedRoleManagerServer) testEmbeddedByValue()                     {}

// UnsafeRoleManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleManagerServer will
// result in compilation errors.
type UnsafeRoleManagerServer interface {
	mustEmbedUnimplementedRoleManagerServer()
}

func RegisterRoleManagerServer(s grpc.ServiceRegistrar, srv RoleManagerServer) {
	// If the following call pancis, it indicates UnimplementedRoleManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleManager_ServiceDesc, srv)
}

func _RoleManager_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManagerServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManager_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManagerServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManager_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManagerServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManager_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManagerServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManager_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManagerServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManager_GetRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManagerServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManager_GetRolesByUIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesByUIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManagerServer).GetRolesByUIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManager_GetRolesByUIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManagerServer).GetRolesByUIDs(ctx, req.(*GetRolesByUIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManager_GetAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManagerServer).GetAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManager_GetAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManagerServer).GetAvailableModels(ctx, req.(*GetAvailableModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleManager_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleManagerServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleManager_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleManagerServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleManager_ServiceDesc is the grpc.ServiceDesc for RoleManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Wittgenstein.v1.RoleManager",
	HandlerType: (*RoleManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _RoleManager_CreateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _RoleManager_DeleteRole_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _RoleManager_GetRoles_Handler,
		},
		{
			MethodName: "GetRolesByUIDs",
			Handler:    _RoleManager_GetRolesByUIDs_Handler,
		},
		{
			MethodName: "GetAvailableModels",
			Handler:    _RoleManager_GetAvailableModels_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _RoleManager_SetRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/role/v1/role.proto",
}
